### PR TITLE
Add support for using custom `Request` and `WebSocket` classes.

### PR DESCRIPTION
**Pull request by Goldziher**
# PR Checklist

- [x] Have you followed the guidelines in `CONTRIBUTING.md`?
- [x] Have you got 100% test coverage on new code?
- [ ] Have you updated the prose documentation?
- [x] Have you updated the reference documentation?

This PR adds support for using custom subclasses of `Request` and `WebSocket` in the application by passing these to the Starlite constructor. It forms a solid basis for extension further via plugins. For example, consider an `SQLAlchemyRequest` class that has properties to access the session etc.

### CODE REVIEW

**Review by cofin — APPROVED** [review]

**Review by odiseo0 — COMMENTED** [review]
Should we fix the warning before we merge or it doesn't matter?

**Comment by cofin** [comment]
We should fix it

**Comment by cofin** [comment]
Is this an actual error?  It sure looks like `Any` is still being used to me: 
```python
request: "Request[Any, Any]" = scope["app"].request_class(scope=scope)
```

**Comment by cofin** [comment]
I think this is an erroneous error.  Pre-commit also completed successfully and it would have raised an error if it was actually unused.

**Pull request merged**
