### PR TITLE
Enhancement:  Picologging Support

### PR DESCRIPTION
**Pull request by cofin**
This enhancement will automatically enable Picologging if the package is installed.  Use the `picologging` extra to install with Starlite or manually add the dependency.

### CODE REVIEW

**Review by Goldziher — APPROVED** [review]
Looks good. Merge when ready and tests are in place.

**Review by peterschutt — APPROVED** [review]
Nice!

**Comment by cofin** [comment]
I'm going to merge the latest changes, update the documentation, and merge this, if you are both ok with it.  We can create another PR if there are any changes required once picologging integrates their own dictConfig.

**Comment by Goldziher** [comment]
Sure

**Pull request merged**
