### PR TITLE
Changes CHANGELOG.md to descending order.

### PR DESCRIPTION
**Pull request by peterschutt**
This PR reorders CHANGELOG.md to descending order.

As the number of releases grows, this puts the more relevant data to the top of the file, making it more user-friendly.

# PR Checklist

- [x] Have you followed the guidelines in `CONTRIBUTING.md`?
- [x] Have you got 100% test coverage on new code?
- [x] Have you updated the prose documentation?
- [x] Have you updated the reference documentation?

### CODE REVIEW

**Review by Goldziher — APPROVED** [review]
If you are editing this stuff - can you make it more consistent as well?

**Comment by peterschutt** [comment]
> If you are editing this stuff - can you make it more consistent as well?

For example?

**Comment by Goldziher** [comment]
> > If you are editing this stuff - can you make it more consistent as well?
> 
> For example?

not really crucial, but casing of words for example etc.

**Comment by peterschutt** [comment]
> > > If you are editing this stuff - can you make it more consistent as well?
> > 
> > 
> > For example?
> 
> not really crucial, but casing of words for example etc.

OK, sure. I just ran a script over it and didn't really read any of it :)

**Pull request merged**
