### PR TITLE
Add test for content type when using before request handler

### PR DESCRIPTION
**Pull request by tompin82**
When using a before request handler with a route with  a `Template` response, the return annotation is set to `T` which causes the the response to be serialized as JSON instead .

It seems to stem from this part of the `HTTPRouteHandler` class:

```python
if before_request_handler := self.resolve_before_request():
        before_request_handler_signature = Signature.from_callable(before_request_handler)
        if (
            before_request_handler_signature.return_annotation
            and before_request_handler_signature.return_annotation is not Signature.empty
        ):
            return_annotation = before_request_handler_signature.return_annotation
```

### Pull Request Checklist

[//]: # "Please review the [Starlite contribution guidelines](https://github.com/starlite-api/starlite/blob/main/CONTRIBUTING.rst) for this repository."

- [ ] New code has 100% test coverage
- [ ] (If applicable) The prose documentation has been updated to reflect the changes introduced by this PR
- [ ] (If applicable) The reference documentation has been updated to reflect the changes introduced by this PR

By submitting this issue, you agree to:

- follow Starlite's [Code of Conduct](https://github.com/starlite-api/.github/blob/main/CODE_OF_CONDUCT.md)
- follow Starlite's [Contribution Guidelines](https://starliteproject.dev/community/contribution-guide)

### CODE REVIEW

**Comment by Goldziher** [comment]
Great!

@all-contributors add @tompin82 tests

**Review by Goldziher — APPROVED** [review]
Great. We will merge it into a fix branch, when we start working on it.

**Comment by peterschutt** [comment]
Pretty much anywhere that we use `Signature.from_callable(...)` to inspect a return annotation is flawed for the forward-reference annotation case.

**Comment by Goldziher** [comment]
@peterschutt - should we try fixing this before your DTO stuff is in place or wait?

**Comment by peterschutt** [comment]
Thanks @tompin82 - I merged your test into #1452 - closing this in favor of that one.

**Pull request closed without merging**
