### PR TITLE
Fix expected OpenAPI components in `test_merged_components_correct`

### PR DESCRIPTION
**Pull request by Gamazic**
Fix expected OpenAPI components for [this PR](https://github.com/starlite-api/pydantic-openapi-schema/pull/18). Removed the `explode` element, because now `explode` is `None` by default.

# PR Checklist

- [x] Have you followed the guidelines in `CONTRIBUTING.md`?
- [ ] Have you got 100% test coverage on new code?
- [ ] Have you updated the prose documentation?
- [ ] Have you updated the reference documentation?

### CODE REVIEW

**Comment by Goldziher** [comment]
can you update `poetry update`

**Comment by Gamazic** [comment]
I can but there is no updated 
`pydantic-openapi-schema`. I guess this is because CI job has failed.

**Comment by Gamazic** [comment]
As I can see we have to make a new release for `pydantic-openapi-schema` in order to publish library to PyPi

**Comment by Goldziher** [comment]
@all-contributors add @Gamazic code

**Pull request merged**
