### PR TITLE
Add support for layered middleware

### PR DESCRIPTION
**Pull request by Goldziher**
This PR addresses the discussion #169. Its currently in draft state - the architecture is in flux and the code is not very clean. Also the tests fail and their failure indicates a problem with the logic which causes the route.handle method not to be evaluated every time. I nonetheless open this now for comments because the changes required here are quite big - and i am not 100% certain about the direction I have taken. So please add comments and lets discuss this.

### CODE REVIEW

**Comment by peterschutt** [comment]
Hey @goldziher - I'm keen to review this and get in and help where I can, but I don't have a lot of time to offer this weekend. I'll have a look tomorrow night most likely. Would it be helpful if I started working on tests?

**Comment by Goldziher** [comment]
> Hey @goldziher - I'm keen to review this and get in and help where I can, but I don't have a lot of time to offer this weekend. I'll have a look tomorrow night most likely. Would it be helpful if I started working on tests?

Any help is appreciated, and we are really not in a rush - let's make sure to get this one right before merging, so the more the merrier.

**Comment by Goldziher** [comment]
Ok, @peterschutt -- this PR is ready for review. code wise. Its missing two components:

1. Comprehensive tests
2. Documentation

Additionally, there is one test that is currently marked with `@skip` because its either flaky or something is amiss. 

If you want to add more tests, or improve this PR in any other way, go ahead and feel free to either push directly to this branch, or branch from it and add a PR that is pointing at it.

**Comment by peterschutt** [comment]
Hey @Goldziher - I've had a quick pass over the changes - nothing stands out to me, although this is covering areas that I'm not super familiar with yet, so prob best for me to focus on testing which will help me to get my head across it all in better depth.

Anything specific you'd like to see added to the tests?

**Comment by Goldziher** [comment]
> Hey @Goldziher - I've had a quick pass over the changes - nothing stands out to me, although this is covering areas that I'm not super familiar with yet, so prob best for me to focus on testing which will help me to get my head across it all in better depth.
> 
> Anything specific you'd like to see added to the tests?

So, we need to test middleware resolution in all levels of the app (app, router, controller, route handler etc.), as well as ensure the integration of levels is correct and the call order of middlewares is correct. You can modify existing tests or write new ones?

**Comment by peterschutt** [comment]
OK sweet, I'll head down that road and will just PR into this branch. I've run out of steam tonight so I'll chip away at it this week :+1:

**Comment by Goldziher** [comment]
TypedDict is a good idea

**Pull request merged**
