### PR TITLE
docs: reduce contrast in light mode code blocks

### PR DESCRIPTION
**Pull request by pemocarlo**
## Before:
Screenshot from 2022-10-22 15-17-38

## After:
Screenshot from 2022-10-22 15-18-05

## Before:
Screenshot from 2022-10-22 15-17-07

## After
Screenshot from 2022-10-22 15-16-29

Let me know if you like the idea and the new colours.

# PR Checklist

- [x] Have you followed the guidelines in `CONTRIBUTING.md`?
- [x] Have you got 100% test coverage on new code?
- [ ] Have you updated the prose documentation?
- [ ] Have you updated the reference documentation

### CODE REVIEW

**Comment by Goldziher** [comment]
@pemocarlo - its a cool contribution! I would very much love to have our docs style improved 😉 . I am on the color blind spectrum, so for me the code blocks you show in the examples are a bit on the harder side to see. If you could make the colors a bit stronger it would be great. Otherwise, I think it looks way better - of course, I am a rather poor judge of this im afraid. 

@dkress59 perhaps you have some input?

**Comment by dkress59** [comment]
I'm on it

**Comment by pemocarlo** [comment]
Hi,
@Goldziher  @dkress59 thank you for your comments. I agree that some of the colours were harder to see without the lighter background, therefore I improved them. Let me know what you think.

Now it looks like this:
Screenshot from 2022-10-23 10-57-05

Screenshot from 2022-10-23 11-00-12

**Comment by Goldziher** [comment]
Looks great to me. I will let @dkress59 approve and merge the PR - when he is satisfied, since he did the original design of the docs.

**Comment by Goldziher** [comment]
@all-contributors add @pemocarlo docs

**Comment by dkress59** [comment]
@pemocarlo those one-liners definitely look better now! I'm not 100% happy with the brownish shade of yellow, but the yellow-on-white/orange-on-white contrast has been an issue, for sure.

I'll try to give the docs a bigger rebrush, but for now this is an improvement, thanks!

**Review by dkress59 — APPROVED** [review]

**Pull request merged**
