### PR TITLE
Fix critical bug in parsing headers

### PR DESCRIPTION
**Pull request by knowsuchagency**
# Description

This bug addresses a bug when parsing HTTP headers from `scope["headers"]`.

Currently, the `parse_headers` function is decorated with `lru_cache` which can't hash lists. 

This is problematic because lists (not tuples) are what the ASGI protocol allows for since they're serializable. 

The ASGI server will pass lists of lists to `parse_headers` leading to `TypeError`.

We are currently running into this bug with starlite `1.51.0`

> Because these messages could be sent over a network, they need to be serializable, and so they are only allowed to contain the following types:

    Byte strings
    Unicode strings
    Integers (within the signed 64-bit range)
    Floating point numbers (within the IEEE 754 double precision range; no Nan or infinities)
    Lists (tuples should be encoded as lists)
    Dicts (keys must be Unicode strings)
    Booleans
    None

This PR maintains the current internal API for `parse_headers` by casting its input to a tuple of tuples and passing it to the original, decorated function.

# PR Checklist

- [x] Have you followed the guidelines in `CONTRIBUTING.rst`?
- [x] Have you got 100% test coverage on new code?
- [x] Have you updated the prose documentation?
- [x] Have you updated the reference documentation?

### CODE REVIEW

**Comment by knowsuchagency** [comment]
@all-contributors please add @knowsuchagency  for bug

**Comment by peterschutt** [comment]
Thanks @knowsuchagency someone will review asap.

**Review by peterschutt — APPROVED** [review]
Thanks again!

**Comment by knowsuchagency** [comment]
Thank you @peterschutt !

**Pull request merged**
